config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users do 
    resources :fridges do
      member do 
        patch :done
      end
    end
  end

  resources :recipes do 
    resources :ingredient
    resources :direction
  end

  post "/search" => "recipes#search"

  resources :sessions

  get "/sign_up" => "users#new"
  get "/sign_in" => "sessions#new"
  get "/sign_out" => "sessions#destroy"


  root "recipes#index"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :ingredients, inverse_of: :recipe,  dependent: :destroy
  has_many :directions, inverse_of: :recipe, dependent: :destroy
  mount_uploader :image, ImageUploader
  validates :title, presence: true
  validates :description, presence: true
  validates :video, presence: true
  validates :image, presence: true
  # YT_LINK_FORMAT = /\A.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|\&v=)([^#\&\?]*).*/i
  # validates :video, presence: true, format: YT_LINK_FORMAT
  accepts_nested_attributes_for :ingredients, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :directions, reject_if: :all_blank, allow_destroy: true

  scope :search, -> (argument) { Recipe.includes(:ingredient).where("ingredient ILIKE :search or title ILIKE :search", search: "%#{argument}%").references(:ingredient)}

  def self.search(search)
    Recipe.where("title ILIKE ?", "%#{search}%")
    Recipe.joins(:ingredients).where("name ILIKE ?", "%#{search}%")
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :find_recipe, only:[:show, :edit, :update, :destroy]
  # before_action :require_user, expect: [:index, :show]

  def index
    @recipe = Recipe.all.order("created_at DESC")
    @user = current_user
    @fridge = Fridge.where(user_id: current_user)
  end

  def new
    @recipe = Recipe.new
    @recipe.ingredients.build
    @recipe.directions.build
  end

  def create
    user = User.find(session[:user_id])
    @recipe = user.recipes.build(recipe_params)
    build_association(@recipe)
    if @recipe.save!
      flash[:notice] = "Congratulation, your recipe has been saved!"
      redirect_to @recipe
    else  
      flash[:notice] = "There is some issues to save your recipe. Please try again"
      render "new"
    end
  end

  def show
    @ingredient = Ingredient.where(recipe_id: @recipe.id)
    @direction = Direction.where(recipe_id: @recipe.id)
    @fridge = Fridge.where(user_id: current_user)
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:notice] = "Recipe has been updated"
      redirect_to @recipe
    else
      render "edit"
    end
  end

  def destroy
    @recipe.destroy
    flash[:notice] = "Successfully deleted!"
    redirect_to root_path
  end

  def search
    @result = Recipe.search(params[:search])
        respond_to do |format|
          format.json { render json: @recipe }
          format.html { render "recipes/search"}
          format.js 
    end 
  end


private

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:title, :description, :user_id, :video, :image, ingredients_attributes: [:id, :name, :amount, :recipe_id, :user_id, :_destroy], directions_attributes: [:id, :step, :recipe_id, :user_id, :_destroy])
  end 

  def build_association(recipe)
    recipe.ingredients.build
    recipe.directions.build    
  end

  # def set_association(ingredient, direction)
  #   recipe.ingredient.each do |ingredient|
  #     ingredient.user = user
  #   end

  #   recipe.direction.each do |direction|
  #     direction.user = user
  #   end
  # end

end

app/helpers/recipe_helper.rb
module RecipeHelper
end

app/views/recipes/_form.html.erb
<p>Title: <%= form.text_field :title %></p>
<p>Image: <%= form.file_field :image %></p>
<p>Description: <%= form.text_field :description %></p>
<p>Video: <%= form.text_field :video %></p>
<p>Ingredient:</p>
<div class="ingredients">
    <%= form.fields_for :ingredients do |ingredient| %>
          <%= render "ingredients/form", f: ingredient %>
        <% end %>
    <div class="links">
    <%= link_to_add_association '+', form, :ingredients, partial: "ingredients/form", class: "btn btn-default add-button"%>
    </div>
</div>
</p>
<p>Direction:</p>
<p>
  <%= form.fields_for :directions do |direction| %>
    <%= render "directions/form", f: direction  %>
  <%end%>
    <div class="links">
    <%= link_to_add_association '+', form, :directions, partial: "directions/form", class: "btn btn-default add-button" %>
    </div>
</p>

app/views/recipes/create.html.erb
<h1>Recipe#create</h1>
<p>Find me in app/views/recipe/create.html.erb</p>

app/views/recipes/destroy.html.erb
<h1>Recipe#destroy</h1>
<p>Find me in app/views/recipe/destroy.html.erb</p>

app/views/recipes/edit.html.erb
<h2><u>Change Recipe?</u></h2>

<%= form_for @recipe do |form|%>
  <%= render partial: "/recipes/form", object: form %>

<div>
  <%= form.submit "Update", data:{confirm: "Change Recipe?"}%>
</div>
<%end%>

app/views/recipes/index.html.erb
<h1>Welcome to EazyRecipe</h1>
<div>

<%= link_to "Got recipe to share?", new_recipe_path, class: "btn btn-default" %>
<br>
<div class="list-index">
<button id="show-list">Show list</button>
<div class="list">
<%= render partial: "/fridges/show" %>
</div>
</div>
</div>
    <div class="search-form">
      <%= form_tag search_path do %>
        <%= label_tag "search" %>
        <%= text_field_tag "search", nil, list: "list", placeholder: "Leftover ingredient?" %>
        <datalist id="list"></datalist>
      <%end%>
    </div>
    

<% @recipe.each_slice(3) do |recipes|%>
<div class="row">
<% recipes.each do |recipe|%>
  <div class="col-md-4">
  <span><%= link_to recipe.title, recipe_path(recipe) %></span>
  <p><%= link_to image_tag(recipe.image_url(:thumb).to_s), recipe_path(recipe) %></p>
  <p>Description: <%= recipe.description %></p>
  <span>By: <%= recipe.user.first_name %></span>
  </div>
<%end%>
</div>
<%end%>

app/views/recipes/new.html.erb
<h1><u>New Recipe</u></h1>

<%= form_for @recipe do |form| %>
  <%= render partial: "/recipes/form", object: form %>




<div>
  <%= form.submit "Save", data: { confirm: "Save Recipe?" }%>
</div>
<%end%>

app/views/recipes/search.html.erb
<div class="search-form">
    <%= form_tag search_path do %>
      <%= label_tag "search" %>
      <%= text_field_tag "search", nil, list: "list", placeholder: "Search again?"%>
      <datalist id="list"></datalist>
    <%end%>
</div>
Search result: <%= "#{params[:search]}"%>
<% if @result.empty?%>
<p>There is no recipe match found!</p>
<%else%>
<% @result.each_slice(3) do |recipes|%>
<div class="row">
<% recipes.each do |recipe|%>
  <div class="col-md-4">
  <span><%= link_to recipe.title, recipe_path(recipe) %></span>
  <p><%= link_to image_tag(recipe.image_url(:thumb).to_s), recipe_path(recipe) %></p>
  <p>Description: <%= recipe.description %></p>
  <span>By: <%= recipe.user.first_name %></span>
  </div>
<%end%>
</div>
<%end%>
<%end%>

app/views/recipes/show.html.erb
<div class="show-list">
<button id="show-list">Show list</button>
<div class="list">
<%= render partial: "/fridges/show" %>
</div>
</div>

<div class="show-recipe">
<p><%= image_tag(@recipe.image_url.to_s) %></p>
<p>Title: <%= @recipe.title %></p> 
<p>Description: <%= @recipe.description %></p> 

<p><iframe src='https://www.youtube.com/embed/<%= @recipe.video %>?rel=0&autoplay=<%= params[:autoplay] || 0 %>' frameborder='0' allowfullscreen></iframe></p> 
<p>By: <%= @recipe.user.first_name %></p>
<p>Ingredient:
<p>
<% @ingredient.each do |ingredient|%>
<span><%= ingredient.amount %></span> 
<%= ingredient.name %> 
</p>
<%end%>
<p>Direction:
<p>
<% @direction.each_with_index do |direction, index|%>
  <%= index + 1%>
  <%= direction.step %>
</p>
  <%end%>
</p>
</p>
<div id="map" style="width: 50%; height: 200px; background-color: grey;"></div>
<script>
      function initMap() {
        var uluru = {lat: 3.1390, lng: 101.6869};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 6,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
  </script>
    <script async defer
    src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['GOOGLE_API_KEY']%>&callback=initMap">
    </script>
<div>
<%if @recipe.user == current_user %>
<%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
<%= link_to "Delete", recipe_path, method: :delete, data:{confirm:"Are you sure?"}, class: "btn btn-default"%>
<%end%>
<%= link_to "Back", root_path, class: "btn btn-default" %>
</div>
</div>

app/views/recipes/update.html.erb
<h1>Recipe#update</h1>
<p>Find me in app/views/recipe/update.html.erb</p>