config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users do 
    resources :fridges do
      member do 
        patch :done
      end
    end
  end

  resources :recipes do 
    resources :ingredient
    resources :direction
  end

  post "/search" => "recipes#search"

  resources :sessions

  get "/sign_up" => "users#new"
  get "/sign_in" => "sessions#new"
  get "/sign_out" => "sessions#destroy"


  root "recipes#index"
end

app/models/fridge.rb
class Fridge < ApplicationRecord
  belongs_to :user, foreign_key: "user_id"
  
end

app/controllers/fridges_controller.rb
class FridgesController < ApplicationController
before_action :find_user, only:[:index, :new, :create, :edit, :update, :destroy]
before_action :set_fridge, only:[:edit, :update, :destroy]

def index
   @fridge = Fridge.where(user_id: current_user)
end

def new
  @fridge = Fridge.new
end

def create
  @fridge = @user.fridges.new(fridge_params)
  @fridge.user_id = @user.id
  if @fridge.save
    redirect_to @user
  else
    render "new"
  end
end

def show
  @fridge = Fridge.where(user_id: current_user)
end

def destroy
  if @fridge.delete
  flash[:notice] = "Item destroy!"
  redirect_to @user
  else
    flash[:notice] = "Error deleting item."
  end
end

private

  def set_fridge
     @fridge = Fridge.find(params[:id])
  end
  def find_user
    @user = User.find(session[:user_id])
  end

def fridge_params
  params.require(:fridge).permit(:title, :user_id, :name, :amount, :done)
end

end

app/views/fridges/_form.html.erb
<div class="nested-fields">
<span>Name: <%= form.text_field :name %></span>
<span><%= form.select :amount, options_for_select((0..20)), :class => 'genForm_dropBox' %></span>
<!-- <span>Finished?: <%#= form.check_box :done %></span> -->
<span><%#= link_to_remove_association "-", form, class: "btn btn-default" %></span>
</div>

app/views/fridges/_show.html.erb
<div>
<div>
<div><strong><u><%= " #{current_user.first_name}'s Grocery List:"%></u></strong></div>

  <% if @fridge.empty? %>
    Please add ingredient to your list.
  <%else%>
  <table>
  <thead>
  <th>NO.</th>
  <th>Name</th>
  <th>Amount</th>
 <!--  <th>Finished?</th> -->
  </thead>
  <% @fridge.each_with_index do |fridge, index|%>
  <tbody>
  <td><%= index + 1%></td>
  <td><%= fridge.name %></td>
  <td><%= fridge.amount %></td>
  <td><%#= fridge.done %></td>
  <td><%= link_to "-", user_fridge_path(current_user,fridge.id), method: :delete, remote: true, data: {confirm:"Are you sure?"}, class: "btn btn-default"%>
  </td>
</tbody>
<%end%>
</table>
    
  </div>
  <%end%>
<p><%= form_for ([current_user, current_user.fridges.build]) do |form|%>
    <%= render partial: "fridges/form", object: form%>
      <%#= link_to_add_association '+', form, :fridge, partial: "fridges/form", class: "btn btn-default add-button"%>
    <%= form.submit "+", remote: true %>
  <%end%></p>
</div>

app/views/fridges/create.js.erb
$('td').append("<%= j render partial: 'show', locals: {fridge: @fridge} %>")
$('table')[0].reset();

app/views/fridges/destroy.js.erb
$('td#fridge_<%= @fridge.id %>').slideUp();
$('table')[0].reset();

app/views/fridges/new.html.erb
<div><%= "#{@user.first_name}'s List"%></div> 
  <div>
  <%= form_for ([@user, @user.fridges.build]) do |form|%>
    <%= render partial: "fridges/form", object: form%>
      <%#= link_to_add_association '+', form, :fridge, partial: "fridges/form", class: "btn btn-default add-button"%>
    <%= form.submit "+"%>
  </div>
  <%end%>