config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :users do 
    resources :fridges do
      member do 
        patch :done
      end
    end
  end

  resources :recipes do 
    resources :ingredient
    resources :direction
  end

  post "/search" => "recipes#search"

  resources :sessions

  get "/sign_up" => "users#new"
  get "/sign_in" => "sessions#new"
  get "/sign_out" => "sessions#destroy"


  root "recipes#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EazyRecipe</title>
    <%= csrf_meta_tags %>

    <!-- <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script> -->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.js"></script>
    <!-- <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/selectize.js/0.12.4/js/selectize.js"></script> -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>

  </head>
  <body>
  <nav class="navbar navbar-default">
    <nav class="navbar navbar-dark bg-dark">
      <div class="container-fluid">
        <%= link_to "EazyRecipe", root_path, class: "navbar-brand"%>
    <div class="navbar-text navbar-right">
        <% if logged_in? %>
        <span class="btn btn-default"><%= link_to "Signed in as #{current_user.first_name}", user_path(current_user) %></span>
        <%= link_to "Logout", sign_out_path, class: "btn btn-primary"%>
        <%else%>
        <%= link_to "Sign Up", sign_up_path, class: "btn btn-primary" %>
        <%= link_to "Login", sign_in_path, class: "btn btn-primary" %>
        </div>
        <%end%>
    </div>
  </nav>
  </nav>
  <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
        <div class="container">
          <%= yield %>
        </div>
  </body>
  <footer>
  </footer>
</html>